version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "NathanOrme"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "NathanOrme"

  - package-ecosystem: "npm"
    directory: "/src/main/frontend/"
    schedule:
      interval: "daily"
    assignees:
      - "NathanOrme"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "NathanOrme"
