version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"